spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: file_status_db

kafka:
  bootstrap-servers: kafka1:9092
  topic:
    status: file-status-topic

file:
  status:
    max-retries: 3
