server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

kafka:
  bootstrap-servers: localhost:9092
  topic:
    upload: file-upload-topic
    status: file-status-topic

file:
  validation:
    allowed-extensions:
      - xls
      - xlsx
    max-size: 5242880
